export const styles = {
  layout: {
    display: "flex",
    height: "100vh",
    overflow: "hidden",
  },
  sidebar: {
    width: 220,
    flexShrink: 0,
    background: "var(--bg-elevated)",
    borderRight: "1px solid var(--border-subtle)",
    display: "flex",
    flexDirection: "column",
    padding: "20px 0",
    overflow: "hidden",
  },
  backBtn: {
    background: "none",
    border: "none",
    color: "var(--text-tertiary)",
    fontSize: 12,
    padding: "0 16px 16px",
    cursor: "pointer",
    textAlign: "left",
  },
  groupMeta: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "0 16px 20px",
    borderBottom: "1px solid var(--border-subtle)",
    marginBottom: 12,
  },
  groupIcon: {
    width: 32,
    height: 32,
    background: "var(--accent-rust)",
    borderRadius: 6,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 14,
    fontWeight: 700,
    color: "var(--accent-on-rust)",
    flexShrink: 0,
  },
  groupName: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    lineHeight: 1.3,
  },
  groupPath: {
    fontSize: 10.5,
    color: "var(--text-tertiary)",
    marginTop: 2,
  },
  nav: {
    display: "flex",
    flexDirection: "column",
    padding: "0 8px",
    gap: 2,
  },
  navItem: {
    background: "none",
    border: "none",
    borderRadius: 5,
    padding: "7px 10px",
    textAlign: "left",
    fontSize: 13,
    color: "var(--text-secondary)",
    cursor: "pointer",
  },
  navItemActive: {
    background: "var(--bg-elevated-2)",
    color: "var(--text-primary)",
    fontWeight: 600,
  },
  main: {
    flex: 1,
    overflowY: "auto",
    height: "100vh",
  },
  panel: {
    maxWidth: 860,
    margin: "0 auto",
    padding: "40px 32px",
  },
  panelEmpty: {
    padding: "60px 40px",
    textAlign: "center",
  },
  chatLayout: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
  },
  chatHistory: {
    flex: 1,
    overflowY: "auto",
    padding: "24px 32px",
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  chatEmpty: {
    padding: "40px 0",
  },
  chatMsg: {
    maxWidth: 720,
    padding: "12px 16px",
    borderRadius: 8,
  },
  chatMsgUser: {
    alignSelf: "flex-end",
    background: "var(--bg-elevated-2)",
  },
  chatMsgBot: {
    alignSelf: "flex-start",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-subtle)",
  },
  chatMsgRole: {
    fontSize: 10.5,
    fontWeight: 600,
    color: "var(--text-tertiary)",
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  chatMsgContent: {
    fontSize: 14,
    color: "var(--text-primary)",
    lineHeight: 1.6,
  },
  chatSources: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 8,
  },
  sourceChip: {
    fontSize: 10.5,
    background: "var(--bg-elevated-2)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 4,
    padding: "2px 6px",
    color: "var(--text-tertiary)",
    fontFamily: "var(--font-mono)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    maxWidth: 200,
  },
  chatForm: {
    display: "flex",
    gap: 8,
    padding: "12px 32px 20px",
    borderTop: "1px solid var(--border-subtle)",
    flexShrink: 0,
  },
  chatInput: {
    flex: 1,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 6,
    padding: "10px 14px",
    fontSize: 13,
    color: "var(--text-primary)",
    outline: "none",
  },
  chatSendBtn: {
    background: "var(--accent-rust)",
    border: "none",
    borderRadius: 6,
    padding: "10px 18px",
    fontSize: 13,
    fontWeight: 600,
    color: "var(--accent-on-rust)",
    cursor: "pointer",
  },
  pageTitle: {
    fontFamily: "var(--font-serif)",
    fontSize: 32,
    fontWeight: 700,
    margin: "0 0 28px",
    color: "var(--text-primary)",
  },
  sectionTitle: {
    fontFamily: "var(--font-serif)",
    fontSize: 22,
    fontWeight: 600,
    margin: "0 0 8px",
    color: "var(--text-primary)",
  },
  sectionHint: {
    fontSize: 13,
    color: "var(--text-secondary)",
    margin: "0 0 20px",
  },
  emptyText: {
    fontFamily: "var(--font-serif)",
    fontSize: 15,
    color: "var(--text-secondary)",
    lineHeight: 1.6,
  },
  markdownBody: {
    fontSize: 14,
    lineHeight: 1.7,
    color: "var(--text-primary)",
  },
  repoList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  repoCard: {
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 8,
    padding: "14px 16px",
    cursor: "pointer",
  },
  repoCardName: {
    fontFamily: "var(--font-serif)",
    fontSize: 16,
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  repoCardPath: {
    fontSize: 11.5,
    color: "var(--text-tertiary)",
    marginTop: 2,
  },
  repoCardMeta: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
  },
  branchTag: {
    fontSize: 10.5,
    background: "var(--bg-elevated-2)",
    color: "var(--text-secondary)",
    padding: "2px 7px",
    borderRadius: 4,
  },
  ragTag: {
    fontSize: 10.5,
    whiteSpace: "nowrap",
  },
  monorepoTag: {
    fontSize: 10.5,
    background: "rgba(201,124,74,0.15)",
    color: "var(--accent-rust)",
    padding: "2px 7px",
    borderRadius: 4,
  },
  searchForm: {
    display: "flex",
    gap: 8,
    marginBottom: 24,
  },
  searchInput: {
    flex: 1,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 6,
    padding: "10px 14px",
    fontSize: 13,
    color: "var(--text-primary)",
    outline: "none",
  },
  searchBtn: {
    background: "var(--accent-rust)",
    border: "none",
    borderRadius: 6,
    padding: "10px 18px",
    fontSize: 13,
    fontWeight: 600,
    color: "var(--accent-on-rust)",
    cursor: "pointer",
  },
  searchResults: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  resultCard: {
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 8,
    overflow: "hidden",
  },
  resultHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    borderBottom: "1px solid var(--border-subtle)",
    background: "var(--bg-elevated-2)",
  },
  resultRepo: {
    fontSize: 11.5,
    fontWeight: 600,
    color: "var(--accent-rust)",
  },
  resultFile: {
    flex: 1,
    fontSize: 11.5,
    color: "var(--text-tertiary)",
    fontFamily: "var(--font-mono)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  resultScore: {
    fontSize: 10.5,
    color: "var(--text-tertiary)",
    flexShrink: 0,
  },
  resultCode: {
    margin: 0,
    padding: "12px",
    fontSize: 12,
    fontFamily: "var(--font-mono)",
    color: "var(--text-primary)",
    overflowX: "auto",
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
    maxHeight: 200,
    overflowY: "auto",
  },
};

