import { useState, useRef } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { api } from "../api/client";
import { styles } from "./GroupWikiView.styles";

/**
 * Main view for an indexed GitLab group.
 *
 * Panels:
 * - Overview: group wiki markdown generated by AI
 * - Repos: list of indexed repos with links to open each one
 * - Search: cross-repo semantic search
 * - Chat: cross-repo RAG chat
 */
export function GroupWikiView({ group, onReset, onOpenRepository }) {
  const [activeTab, setActiveTab] = useState("overview");
  const [searchQuery, setSearchQuery] = useState("");
  const [searchResults, setSearchResults] = useState(null);
  const [isSearching, setIsSearching] = useState(false);
  const [chatInput, setChatInput] = useState("");
  const [chatHistory, setChatHistory] = useState([]);
  const [isChatStreaming, setIsChatStreaming] = useState(false);
  const chatEndRef = useRef(null);

  const handleSearch = async (e) => {
    e.preventDefault();
    if (!searchQuery.trim() || isSearching) return;
    setIsSearching(true);
    setSearchResults(null);
    try {
      const res = await api.crossRepoSearch(group.id, searchQuery.trim());
      setSearchResults(res.results || []);
    } catch {
      setSearchResults([]);
    } finally {
      setIsSearching(false);
    }
  };

  const handleChat = async (e) => {
    e.preventDefault();
    if (!chatInput.trim() || isChatStreaming) return;
    const question = chatInput.trim();
    setChatInput("");
    setChatHistory((prev) => [...prev, { role: "user", content: question }]);
    setIsChatStreaming(true);

    let accumulated = "";
    setChatHistory((prev) => [...prev, { role: "assistant", content: "", sources: [] }]);

    try {
      for await (const event of api.streamGroupChat(group.id, question)) {
        if (event.sources) {
          setChatHistory((prev) => {
            const copy = [...prev];
            copy[copy.length - 1] = { ...copy[copy.length - 1], sources: event.sources };
            return copy;
          });
        } else if (event.token) {
          accumulated += event.token;
          setChatHistory((prev) => {
            const copy = [...prev];
            copy[copy.length - 1] = { ...copy[copy.length - 1], content: accumulated };
            return copy;
          });
        }
      }
    } catch (err) {
      setChatHistory((prev) => {
        const copy = [...prev];
        copy[copy.length - 1] = { ...copy[copy.length - 1], content: `*Error: ${err.message}*` };
        return copy;
      });
    } finally {
      setIsChatStreaming(false);
      setTimeout(() => chatEndRef.current?.scrollIntoView({ behavior: "smooth" }), 50);
    }
  };

  return (
    <div style={styles.layout}>
      {/* Sidebar */}
      <aside style={styles.sidebar}>
        <button onClick={onReset} style={styles.backBtn}>← grupos</button>

        <div style={styles.groupMeta}>
          <div style={styles.groupIcon}>G</div>
          <div>
            <div style={styles.groupName}>{group.name || group.group_path}</div>
            <div style={styles.groupPath}>{group.group_path}</div>
          </div>
        </div>

        <nav style={styles.nav}>
          {[
            { key: "overview", label: "Overview" },
            { key: "repos", label: `Repos (${group.repositories?.length || 0})` },
            { key: "search", label: "Búsqueda" },
            { key: "chat", label: "Chat" },
          ].map(({ key, label }) => (
            <button
              key={key}
              onClick={() => setActiveTab(key)}
              style={{ ...styles.navItem, ...(activeTab === key ? styles.navItemActive : {}) }}
            >
              {label}
            </button>
          ))}
        </nav>
      </aside>

      {/* Main content */}
      <main style={styles.main}>
        {activeTab === "overview" && (
          <OverviewPanel overview={group.overview_markdown} groupName={group.name} />
        )}
        {activeTab === "repos" && (
          <ReposPanel repos={group.repositories || []} onOpenRepo={onOpenRepository} />
        )}
        {activeTab === "search" && (
          <SearchPanel
            query={searchQuery}
            onQueryChange={setSearchQuery}
            onSearch={handleSearch}
            results={searchResults}
            isSearching={isSearching}
          />
        )}
        {activeTab === "chat" && (
          <ChatPanel
            history={chatHistory}
            input={chatInput}
            onInputChange={setChatInput}
            onSubmit={handleChat}
            isStreaming={isChatStreaming}
            chatEndRef={chatEndRef}
          />
        )}
      </main>
    </div>
  );
}
function OverviewPanel({ overview, groupName }) {
  if (!overview) {
    return (
      <div style={styles.panelEmpty}>
        <p style={styles.emptyText}>
          El overview del grupo aún no se ha generado. Espera a que el indexado complete.
        </p>
      </div>
    );
  }
  return (
    <div style={styles.panel}>
      <h1 style={styles.pageTitle}>{groupName}</h1>
      <div style={styles.markdownBody}>
        <ReactMarkdown remarkPlugins={[remarkGfm]}>{overview}</ReactMarkdown>
      </div>
    </div>
  );
}

function ReposPanel({ repos, onOpenRepo }) {
  if (!repos.length) {
    return (
      <div style={styles.panelEmpty}>
        <p style={styles.emptyText}>No hay repositorios indexados en este grupo todavía.</p>
      </div>
    );
  }
  return (
    <div style={styles.panel}>
      <h2 style={styles.sectionTitle}>Repositorios</h2>
      <ul style={styles.repoList}>
        {repos.map((repo) => (
          <li key={repo.id} style={styles.repoCard} onClick={() => onOpenRepo(repo)}>
            <div style={styles.repoCardName}>{repo.name}</div>
            <div style={styles.repoCardPath}>{repo.project_path}</div>
            <div style={styles.repoCardMeta}>
              <span style={styles.branchTag}>{repo.default_branch}</span>
              <span style={{
                ...styles.ragTag,
                color: repo.indexed_in_qdrant ? "var(--accent-sage)" : "var(--text-tertiary)",
              }}>
                ● {repo.indexed_in_qdrant ? "RAG activo" : "solo wiki"}
              </span>
              {repo.is_monorepo && <span style={styles.monorepoTag}>monorepo</span>}
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}

function SearchPanel({ query, onQueryChange, onSearch, results, isSearching }) {
  return (
    <div style={styles.panel}>
      <h2 style={styles.sectionTitle}>Búsqueda cross-repo</h2>
      <p style={styles.sectionHint}>
        Busca semánticamente en el código de todos los repositorios del grupo a la vez.
      </p>
      <form onSubmit={onSearch} style={styles.searchForm}>
        <input
          type="text"
          value={query}
          onChange={(e) => onQueryChange(e.target.value)}
          placeholder="Busca cualquier función, clase o concepto..."
          style={styles.searchInput}
          autoFocus
        />
        <button type="submit" disabled={isSearching} style={styles.searchBtn}>
          {isSearching ? "Buscando…" : "Buscar"}
        </button>
      </form>

      {results !== null && (
        <div style={styles.searchResults}>
          {results.length === 0 ? (
            <p style={styles.emptyText}>Sin resultados para esta búsqueda.</p>
          ) : (
            results.map((r, i) => (
              <div key={i} style={styles.resultCard}>
                <div style={styles.resultHeader}>
                  <span style={styles.resultRepo}>{r.repository_name}</span>
                  <span style={styles.resultFile}>{r.file_path}:{r.start_line}-{r.end_line}</span>
                  <span style={styles.resultScore}>{(r.score * 100).toFixed(0)}%</span>
                </div>
                <pre style={styles.resultCode}>{r.content}</pre>
              </div>
            ))
          )}
        </div>
      )}
    </div>
  );
}

function ChatPanel({ history, input, onInputChange, onSubmit, isStreaming, chatEndRef }) {
  return (
    <div style={styles.chatLayout}>
      <div style={styles.chatHistory}>
        {history.length === 0 && (
          <div style={styles.chatEmpty}>
            <p style={styles.emptyText}>
              Pregunta cualquier cosa sobre los repositorios del grupo. Combina contexto de múltiples repos.
            </p>
          </div>
        )}
        {history.map((msg, i) => (
          <div key={i} style={{ ...styles.chatMsg, ...(msg.role === "user" ? styles.chatMsgUser : styles.chatMsgBot) }}>
            <div style={styles.chatMsgRole}>{msg.role === "user" ? "Tú" : "AI"}</div>
            {msg.role === "assistant" ? (
              <div style={styles.markdownBody}>
                <ReactMarkdown remarkPlugins={[remarkGfm]}>{msg.content || "…"}</ReactMarkdown>
              </div>
            ) : (
              <div style={styles.chatMsgContent}>{msg.content}</div>
            )}
            {msg.sources && msg.sources.length > 0 && (
              <div style={styles.chatSources}>
                {msg.sources.slice(0, 3).map((s, si) => (
                  <span key={si} style={styles.sourceChip}>{s.file_path}</span>
                ))}
              </div>
            )}
          </div>
        ))}
        <div ref={chatEndRef} />
      </div>

      <form onSubmit={onSubmit} style={styles.chatForm}>
        <input
          type="text"
          value={input}
          onChange={(e) => onInputChange(e.target.value)}
          placeholder="Pregunta sobre cualquier repo del grupo..."
          style={styles.chatInput}
          disabled={isStreaming}
        />
        <button type="submit" style={styles.chatSendBtn} disabled={isStreaming || !input.trim()}>
          {isStreaming ? "…" : "Enviar"}
        </button>
      </form>
    </div>
  );
}
