import { useState, useRef } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { api } from "../api/client";

/**
 * Main view for an indexed GitLab group.
 *
 * Panels:
 * - Overview: group wiki markdown generated by AI
 * - Repos: list of indexed repos with links to open each one
 * - Search: cross-repo semantic search
 * - Chat: cross-repo RAG chat
 */
export function GroupWikiView({ group, onReset, onOpenRepository }) {
  const [activeTab, setActiveTab] = useState("overview");
  const [searchQuery, setSearchQuery] = useState("");
  const [searchResults, setSearchResults] = useState(null);
  const [isSearching, setIsSearching] = useState(false);
  const [chatInput, setChatInput] = useState("");
  const [chatHistory, setChatHistory] = useState([]);
  const [isChatStreaming, setIsChatStreaming] = useState(false);
  const chatEndRef = useRef(null);

  const handleSearch = async (e) => {
    e.preventDefault();
    if (!searchQuery.trim() || isSearching) return;
    setIsSearching(true);
    setSearchResults(null);
    try {
      const res = await api.crossRepoSearch(group.id, searchQuery.trim());
      setSearchResults(res.results || []);
    } catch (err) {
      setSearchResults([]);
    } finally {
      setIsSearching(false);
    }
  };

  const handleChat = async (e) => {
    e.preventDefault();
    if (!chatInput.trim() || isChatStreaming) return;
    const question = chatInput.trim();
    setChatInput("");
    setChatHistory((prev) => [...prev, { role: "user", content: question }]);
    setIsChatStreaming(true);

    let accumulated = "";
    const botIdx = chatHistory.length + 1;
    setChatHistory((prev) => [...prev, { role: "assistant", content: "", sources: [] }]);

    try {
      for await (const event of api.streamGroupChat(group.id, question)) {
        if (event.sources) {
          setChatHistory((prev) => {
            const copy = [...prev];
            copy[copy.length - 1] = { ...copy[copy.length - 1], sources: event.sources };
            return copy;
          });
        } else if (event.token) {
          accumulated += event.token;
          setChatHistory((prev) => {
            const copy = [...prev];
            copy[copy.length - 1] = { ...copy[copy.length - 1], content: accumulated };
            return copy;
          });
        }
      }
    } catch (err) {
      setChatHistory((prev) => {
        const copy = [...prev];
        copy[copy.length - 1] = { ...copy[copy.length - 1], content: `*Error: ${err.message}*` };
        return copy;
      });
    } finally {
      setIsChatStreaming(false);
      setTimeout(() => chatEndRef.current?.scrollIntoView({ behavior: "smooth" }), 50);
    }
  };

  return (
    <div style={styles.layout}>
      {/* Sidebar */}
      <aside style={styles.sidebar}>
        <button onClick={onReset} style={styles.backBtn}>← grupos</button>

        <div style={styles.groupMeta}>
          <div style={styles.groupIcon}>G</div>
          <div>
            <div style={styles.groupName}>{group.name || group.group_path}</div>
            <div style={styles.groupPath}>{group.group_path}</div>
          </div>
        </div>

        <nav style={styles.nav}>
          {[
            { key: "overview", label: "Overview" },
            { key: "repos", label: `Repos (${group.repositories?.length || 0})` },
            { key: "search", label: "Búsqueda" },
            { key: "chat", label: "Chat" },
          ].map(({ key, label }) => (
            <button
              key={key}
              onClick={() => setActiveTab(key)}
              style={{ ...styles.navItem, ...(activeTab === key ? styles.navItemActive : {}) }}
            >
              {label}
            </button>
          ))}
        </nav>
      </aside>

      {/* Main content */}
      <main style={styles.main}>
        {activeTab === "overview" && (
          <OverviewPanel overview={group.overview_markdown} groupName={group.name} />
        )}
        {activeTab === "repos" && (
          <ReposPanel repos={group.repositories || []} onOpenRepo={onOpenRepository} />
        )}
        {activeTab === "search" && (
          <SearchPanel
            query={searchQuery}
            onQueryChange={setSearchQuery}
            onSearch={handleSearch}
            results={searchResults}
            isSearching={isSearching}
          />
        )}
        {activeTab === "chat" && (
          <ChatPanel
            history={chatHistory}
            input={chatInput}
            onInputChange={setChatInput}
            onSubmit={handleChat}
            isStreaming={isChatStreaming}
            chatEndRef={chatEndRef}
          />
        )}
      </main>
    </div>
  );
}

function OverviewPanel({ overview, groupName }) {
  if (!overview) {
    return (
      <div style={styles.panelEmpty}>
        <p style={styles.emptyText}>
          El overview del grupo aún no se ha generado. Espera a que el indexado complete.
        </p>
      </div>
    );
  }
  return (
    <div style={styles.panel}>
      <h1 style={styles.pageTitle}>{groupName}</h1>
      <div style={styles.markdownBody}>
        <ReactMarkdown remarkPlugins={[remarkGfm]}>{overview}</ReactMarkdown>
      </div>
    </div>
  );
}

function ReposPanel({ repos, onOpenRepo }) {
  if (!repos.length) {
    return (
      <div style={styles.panelEmpty}>
        <p style={styles.emptyText}>No hay repositorios indexados en este grupo todavía.</p>
      </div>
    );
  }
  return (
    <div style={styles.panel}>
      <h2 style={styles.sectionTitle}>Repositorios</h2>
      <ul style={styles.repoList}>
        {repos.map((repo) => (
          <li key={repo.id} style={styles.repoCard} onClick={() => onOpenRepo(repo)}>
            <div style={styles.repoCardName}>{repo.name}</div>
            <div style={styles.repoCardPath}>{repo.project_path}</div>
            <div style={styles.repoCardMeta}>
              <span style={styles.branchTag}>{repo.default_branch}</span>
              <span style={{
                ...styles.ragTag,
                color: repo.indexed_in_qdrant ? "var(--accent-sage)" : "var(--text-tertiary)",
              }}>
                ● {repo.indexed_in_qdrant ? "RAG activo" : "solo wiki"}
              </span>
              {repo.is_monorepo && <span style={styles.monorepoTag}>monorepo</span>}
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}

function SearchPanel({ query, onQueryChange, onSearch, results, isSearching }) {
  return (
    <div style={styles.panel}>
      <h2 style={styles.sectionTitle}>Búsqueda cross-repo</h2>
      <p style={styles.sectionHint}>
        Busca semánticamente en el código de todos los repositorios del grupo a la vez.
      </p>
      <form onSubmit={onSearch} style={styles.searchForm}>
        <input
          type="text"
          value={query}
          onChange={(e) => onQueryChange(e.target.value)}
          placeholder="Busca cualquier función, clase o concepto..."
          style={styles.searchInput}
          autoFocus
        />
        <button type="submit" disabled={isSearching} style={styles.searchBtn}>
          {isSearching ? "Buscando…" : "Buscar"}
        </button>
      </form>

      {results !== null && (
        <div style={styles.searchResults}>
          {results.length === 0 ? (
            <p style={styles.emptyText}>Sin resultados para esta búsqueda.</p>
          ) : (
            results.map((r, i) => (
              <div key={i} style={styles.resultCard}>
                <div style={styles.resultHeader}>
                  <span style={styles.resultRepo}>{r.repository_name}</span>
                  <span style={styles.resultFile}>{r.file_path}:{r.start_line}-{r.end_line}</span>
                  <span style={styles.resultScore}>{(r.score * 100).toFixed(0)}%</span>
                </div>
                <pre style={styles.resultCode}>{r.content}</pre>
              </div>
            ))
          )}
        </div>
      )}
    </div>
  );
}

function ChatPanel({ history, input, onInputChange, onSubmit, isStreaming, chatEndRef }) {
  return (
    <div style={styles.chatLayout}>
      <div style={styles.chatHistory}>
        {history.length === 0 && (
          <div style={styles.chatEmpty}>
            <p style={styles.emptyText}>
              Pregunta cualquier cosa sobre los repositorios del grupo. Combina contexto de múltiples repos.
            </p>
          </div>
        )}
        {history.map((msg, i) => (
          <div key={i} style={{ ...styles.chatMsg, ...(msg.role === "user" ? styles.chatMsgUser : styles.chatMsgBot) }}>
            <div style={styles.chatMsgRole}>{msg.role === "user" ? "Tú" : "AI"}</div>
            {msg.role === "assistant" ? (
              <div style={styles.markdownBody}>
                <ReactMarkdown remarkPlugins={[remarkGfm]}>{msg.content || "…"}</ReactMarkdown>
              </div>
            ) : (
              <div style={styles.chatMsgContent}>{msg.content}</div>
            )}
            {msg.sources && msg.sources.length > 0 && (
              <div style={styles.chatSources}>
                {msg.sources.slice(0, 3).map((s, si) => (
                  <span key={si} style={styles.sourceChip}>{s.file_path}</span>
                ))}
              </div>
            )}
          </div>
        ))}
        <div ref={chatEndRef} />
      </div>

      <form onSubmit={onSubmit} style={styles.chatForm}>
        <input
          type="text"
          value={input}
          onChange={(e) => onInputChange(e.target.value)}
          placeholder="Pregunta sobre cualquier repo del grupo..."
          style={styles.chatInput}
          disabled={isStreaming}
        />
        <button type="submit" style={styles.chatSendBtn} disabled={isStreaming || !input.trim()}>
          {isStreaming ? "…" : "Enviar"}
        </button>
      </form>
    </div>
  );
}

const styles = {
  layout: {
    display: "flex",
    height: "100vh",
    overflow: "hidden",
  },
  sidebar: {
    width: 220,
    flexShrink: 0,
    background: "var(--bg-elevated)",
    borderRight: "1px solid var(--border-subtle)",
    display: "flex",
    flexDirection: "column",
    padding: "20px 0",
    overflow: "hidden",
  },
  backBtn: {
    background: "none",
    border: "none",
    color: "var(--text-tertiary)",
    fontSize: 12,
    padding: "0 16px 16px",
    cursor: "pointer",
    textAlign: "left",
  },
  groupMeta: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "0 16px 20px",
    borderBottom: "1px solid var(--border-subtle)",
    marginBottom: 12,
  },
  groupIcon: {
    width: 32,
    height: 32,
    background: "var(--accent-rust)",
    borderRadius: 6,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 14,
    fontWeight: 700,
    color: "#1A1410",
    flexShrink: 0,
  },
  groupName: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    lineHeight: 1.3,
  },
  groupPath: {
    fontSize: 10.5,
    color: "var(--text-tertiary)",
    marginTop: 2,
  },
  nav: {
    display: "flex",
    flexDirection: "column",
    padding: "0 8px",
    gap: 2,
  },
  navItem: {
    background: "none",
    border: "none",
    borderRadius: 5,
    padding: "7px 10px",
    textAlign: "left",
    fontSize: 13,
    color: "var(--text-secondary)",
    cursor: "pointer",
  },
  navItemActive: {
    background: "var(--bg-elevated-2)",
    color: "var(--text-primary)",
    fontWeight: 600,
  },
  main: {
    flex: 1,
    overflowY: "auto",
    height: "100vh",
  },
  panel: {
    maxWidth: 860,
    margin: "0 auto",
    padding: "40px 32px",
  },
  panelEmpty: {
    padding: "60px 40px",
    textAlign: "center",
  },
  chatLayout: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
  },
  chatHistory: {
    flex: 1,
    overflowY: "auto",
    padding: "24px 32px",
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  chatEmpty: {
    padding: "40px 0",
  },
  chatMsg: {
    maxWidth: 720,
    padding: "12px 16px",
    borderRadius: 8,
  },
  chatMsgUser: {
    alignSelf: "flex-end",
    background: "var(--bg-elevated-2)",
  },
  chatMsgBot: {
    alignSelf: "flex-start",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-subtle)",
  },
  chatMsgRole: {
    fontSize: 10.5,
    fontWeight: 600,
    color: "var(--text-tertiary)",
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  chatMsgContent: {
    fontSize: 14,
    color: "var(--text-primary)",
    lineHeight: 1.6,
  },
  chatSources: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 8,
  },
  sourceChip: {
    fontSize: 10.5,
    background: "var(--bg-elevated-2)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 4,
    padding: "2px 6px",
    color: "var(--text-tertiary)",
    fontFamily: "var(--font-mono)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    maxWidth: 200,
  },
  chatForm: {
    display: "flex",
    gap: 8,
    padding: "12px 32px 20px",
    borderTop: "1px solid var(--border-subtle)",
    flexShrink: 0,
  },
  chatInput: {
    flex: 1,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 6,
    padding: "10px 14px",
    fontSize: 13,
    color: "var(--text-primary)",
    outline: "none",
  },
  chatSendBtn: {
    background: "var(--accent-rust)",
    border: "none",
    borderRadius: 6,
    padding: "10px 18px",
    fontSize: 13,
    fontWeight: 600,
    color: "#1A1410",
    cursor: "pointer",
  },
  pageTitle: {
    fontFamily: "var(--font-serif)",
    fontSize: 32,
    fontWeight: 700,
    margin: "0 0 28px",
    color: "var(--text-primary)",
  },
  sectionTitle: {
    fontFamily: "var(--font-serif)",
    fontSize: 22,
    fontWeight: 600,
    margin: "0 0 8px",
    color: "var(--text-primary)",
  },
  sectionHint: {
    fontSize: 13,
    color: "var(--text-secondary)",
    margin: "0 0 20px",
  },
  emptyText: {
    fontFamily: "var(--font-serif)",
    fontSize: 15,
    color: "var(--text-secondary)",
    lineHeight: 1.6,
  },
  markdownBody: {
    fontSize: 14,
    lineHeight: 1.7,
    color: "var(--text-primary)",
  },
  repoList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  repoCard: {
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 8,
    padding: "14px 16px",
    cursor: "pointer",
  },
  repoCardName: {
    fontFamily: "var(--font-serif)",
    fontSize: 16,
    fontWeight: 600,
    color: "var(--text-primary)",
  },
  repoCardPath: {
    fontSize: 11.5,
    color: "var(--text-tertiary)",
    marginTop: 2,
  },
  repoCardMeta: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
  },
  branchTag: {
    fontSize: 10.5,
    background: "var(--bg-elevated-2)",
    color: "var(--text-secondary)",
    padding: "2px 7px",
    borderRadius: 4,
  },
  ragTag: {
    fontSize: 10.5,
    whiteSpace: "nowrap",
  },
  monorepoTag: {
    fontSize: 10.5,
    background: "rgba(201,124,74,0.15)",
    color: "var(--accent-rust)",
    padding: "2px 7px",
    borderRadius: 4,
  },
  searchForm: {
    display: "flex",
    gap: 8,
    marginBottom: 24,
  },
  searchInput: {
    flex: 1,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 6,
    padding: "10px 14px",
    fontSize: 13,
    color: "var(--text-primary)",
    outline: "none",
  },
  searchBtn: {
    background: "var(--accent-rust)",
    border: "none",
    borderRadius: 6,
    padding: "10px 18px",
    fontSize: 13,
    fontWeight: 600,
    color: "#1A1410",
    cursor: "pointer",
  },
  searchResults: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  resultCard: {
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 8,
    overflow: "hidden",
  },
  resultHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 12px",
    borderBottom: "1px solid var(--border-subtle)",
    background: "var(--bg-elevated-2)",
  },
  resultRepo: {
    fontSize: 11.5,
    fontWeight: 600,
    color: "var(--accent-rust)",
  },
  resultFile: {
    flex: 1,
    fontSize: 11.5,
    color: "var(--text-tertiary)",
    fontFamily: "var(--font-mono)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  resultScore: {
    fontSize: 10.5,
    color: "var(--text-tertiary)",
    flexShrink: 0,
  },
  resultCode: {
    margin: 0,
    padding: "12px",
    fontSize: 12,
    fontFamily: "var(--font-mono)",
    color: "var(--text-primary)",
    overflowX: "auto",
    whiteSpace: "pre-wrap",
    wordBreak: "break-all",
    maxHeight: 200,
    overflowY: "auto",
  },
};
