export const styles = {
  sidebar: {
    width: 260,
    minWidth: 260,
    height: "100vh",
    borderRight: "1px solid var(--border-subtle)",
    display: "flex",
    flexDirection: "column",
    background: "var(--bg-elevated)",
  },
  repoHeader: {
    padding: "18px 14px 12px",
    borderBottom: "1px solid var(--border-subtle)",
  },
  topRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  backBtn: {
    background: "none",
    border: "none",
    color: "var(--text-tertiary)",
    fontSize: 11,
    padding: 0,
    cursor: "pointer",
  },
  themeBtn: {
    background: "var(--bg-elevated-2)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 4,
    padding: "2px 8px",
    fontSize: 13,
    cursor: "pointer",
    color: "var(--text-secondary)",
    lineHeight: 1.4,
  },
  repoName: {
    fontFamily: "var(--font-serif)",
    fontSize: 17,
    fontWeight: 600,
    color: "var(--text-primary)",
    marginBottom: 3,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  repoPath: {
    fontSize: 11,
    color: "var(--text-tertiary)",
    marginBottom: 10,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  repoMeta: {
    display: "flex",
    gap: 6,
  },
  branchTag: {
    fontSize: 10.5,
    background: "var(--accent-sage-dim)",
    color: "var(--accent-on-sage)",
    padding: "2px 7px",
    borderRadius: 4,
  },
  shaTag: {
    fontSize: 10.5,
    background: "var(--bg-elevated-2)",
    color: "var(--text-tertiary)",
    padding: "2px 7px",
    borderRadius: 4,
  },
  ragTag: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    fontSize: 10,
    marginTop: 8,
  },
  ragDot: {
    fontSize: 8,
  },
  indexedRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
  },
  indexedAt: {
    fontSize: 10,
    color: "var(--text-tertiary)",
  },
  reindexBtn: {
    background: "none",
    border: "1px solid var(--border-subtle)",
    borderRadius: 4,
    padding: "2px 8px",
    fontSize: 10,
    color: "var(--accent-rust)",
    cursor: "pointer",
  },
  actionBtn: {
    marginTop: 8,
    width: "100%",
    background: "var(--bg-elevated-2)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 6,
    padding: "7px 10px",
    fontSize: 11.5,
    color: "var(--text-secondary)",
    textAlign: "left",
    cursor: "pointer",
  },
  exportRow: {
    display: "flex",
    gap: 6,
    marginTop: 6,
  },
  exportBtn: {
    flex: 1,
    background: "var(--bg-elevated-2)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 6,
    padding: "7px 10px",
    fontSize: 11.5,
    color: "var(--text-secondary)",
    textAlign: "center",
    display: "block",
    textDecoration: "none",
  },
  searchWrap: {
    padding: "8px 10px",
    borderBottom: "1px solid var(--border-subtle)",
    position: "relative",
  },
  searchInput: {
    width: "100%",
    background: "var(--bg-elevated-2)",
    border: "1px solid var(--border-subtle)",
    borderRadius: 5,
    padding: "5px 9px",
    fontSize: 11.5,
    color: "var(--text-primary)",
    fontFamily: "var(--font-mono)",
    outline: "none",
  },
  searchSpinner: {
    position: "absolute",
    right: 18,
    top: "50%",
    transform: "translateY(-50%)",
    fontSize: 11,
    color: "var(--text-tertiary)",
  },
  searchExcerpt: {
    fontSize: 10.5,
    color: "var(--text-tertiary)",
    fontFamily: "var(--font-serif)",
    lineHeight: 1.4,
    marginTop: 3,
    overflow: "hidden",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    whiteSpace: "normal",
  },
  nav: {
    flex: 1,
    overflowY: "auto",
    padding: "10px 0",
  },
  noResults: {
    padding: "12px 14px",
    fontSize: 11,
    color: "var(--text-tertiary)",
    fontStyle: "italic",
  },
  navGroup: {
    display: "flex",
    flexDirection: "column",
  },
  navSection: {
    marginTop: 12,
  },
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    background: "none",
    border: "none",
    padding: "2px 14px",
    cursor: "pointer",
  },
  navSectionLabel: {
    fontSize: 10.5,
    letterSpacing: "0.06em",
    color: "var(--text-tertiary)",
  },
  collapseIcon: {
    fontSize: 8,
    color: "var(--text-tertiary)",
  },
  navItem: {
    textAlign: "left",
    border: "none",
    padding: "8px 14px",
    fontSize: 12.5,
    fontFamily: "var(--font-mono)",
    lineHeight: 1.4,
    cursor: "pointer",
    width: "100%",
  },
  keyHint: {
    padding: "8px 12px",
    fontSize: 10,
    color: "var(--text-tertiary)",
    borderTop: "1px solid var(--border-subtle)",
    fontFamily: "var(--font-mono)",
  },
};

